version: '2'
services:
  my_proxy:
    build: ./src
    image: my_proxy_image
    container_name: my_proxy_container
    command: bash -c "./run.sh"
    volumes:
      - ./src:/src
      - ./logs:/var/log/erss
    ports:
      - "12345:12345"

volumes:
